### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by sunjuan1409** [6ix4our/CrmReactDemo#3]
I am very new to TypeScript and just trying to get the sample work first to get a feel for it.
![image](https://user-images.githubusercontent.com/9888707/32026703-15700dce-b9ab-11e7-8b1c-722a6b10cefd.png)

I don't understand the error and don't seem to be able to find any useful articles/discussions addressing similar problems! (?)
Could you please help?

**Comment by 6ix4our** [comment]
@sunjuan1409 Please be sure to install the latest version of TypeScript in your environment.  Visual Studio Code should have done that for you, so I'll check on the current ability to compile the code.  Also, I'm going to include the slide deck I presented in Nashville that covers this project.

TL;DR - The type error is related to the definitions for React, which it shouldn't be, and isn't part of the project I wrote.

**Comment by sunjuan1409** [comment]
Then could you please tell me what I did wrong in the steps?
I am using Visual Studio Code, I chose to clone this Git Repository and supply the URL, I then immediately ran an npm install, and then compile (then failed).
In package.json this is what I see:
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.6",
    "react-scripts-ts": "2.7.0",

  "devDependencies": {
    "@types/jest": "^21.1.0",
    "@types/node": "^8.0.30",
    "@types/react": "^16.0.5",
    "@types/react-dom": "^15.5.4"
  }

**Comment by xavik0f2** [comment]
I got the same error. I tried building the first version and I get the same error. Please help us, your code looks interesting.

```
(3421,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElem
ent>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
```

**Comment by xavik0f2** [comment]
With this I have been able to make the build:

```
"devDependencies": {
    "@types/jest": "^21.1.0",
    "@types/node": "^8.0.30",
    "@types/react": "^15.0.5",
    "@types/react-dom": "^15.5.4",
    "@types/react-test-renderer": "^16.0.0"
  }

```
Now I need to know how can connect this app with my CRM LoL

**Comment by 6ix4our** [comment]
@xavik0f2 So, with the production build, you'll end up with an HTML file, and a JS file.  Put the HTML into CRM in any path structure you prefer, and add the JS to a relative path "below" it (matching the structure of the build output).  It should run perfectly in a vanilla org with test data.  As for the build issues, I'll take a look at factoring the recommendations you've made to see if that fixes the issues seen with the project.

**Comment by xavik0f2** [comment]
It's working! Thanks!!

![image](https://user-images.githubusercontent.com/9109982/32585050-d427440c-c4fb-11e7-8698-dac74c0396fc.png)

**Comment by 6ix4our** [comment]
Created commit fc299b6a2aa3fd1f02f58289f3cd1639c3e23b6d to address this issue.
